---
title: "Bayesian"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulations, with binomial probability distributions


```{r binomial}
likelihoodFunction <- function(p, mC, tC){
  a <- choose(n = tC,k = mC)
  b <- p ^ mC
  c <- (1-p) ^ (tC - mC)
  return(a * b * c)
}

getPoints <- function(mC, tC){
  x <- seq(0, 1, length.out = 200)
  y <- sapply(x, FUN = function(x){likelihoodFunction(p = x, mC = mC, tC = tC)})
  return(cbind(x,y))
}

plot(getPoints(1,5))   ### 2/5
points(getPoints(4,10), col="blue")   ## 4/10
points(getPoints(40,100), col="red")   ## 4/10
points(getPoints(1,3), col = "orange")

optimise(interval = c(0,1),f = likelihoodFunction, mC = 1, tC = 3, maximum = T, tol = 0.001)
```

## Simulations with the conversions of cytosines

Here on bisulfite treatment, cytosine which is non-methylated is converted to tyrosine. Assuming a conversion rate of 99%, i.e., 99% of cytosines which are non-methylated are converted to T.

```{r meths}
error.rates <- 0.02  ### Conversion of 98% 
num.cytosines <- 15

bin.pvals <- numeric()
for (i in seq(num.cytosines)){
  bin.pvals <- c(bin.pvals, binom.test(i,num.cytosines,error.rates)$p.value)
}

plot(seq(num.cytosines), bin.pvals, pch = 19, ylab = "p-val for hypiothesis that read is methylated")
abline(h = 0.05, col = "blue", lwd = 2)
abline(h = 0.01, col = "red", lwd = 2)
#abline(h = 0.05/num.cytosines, col = "red", lwd = 2)



```
